name: Merge Workflows

on:
  workflow_dispatch:
    inputs:
      Tag:
        description: The git tag name to pass to the Python and PowerShell scripts.
        required: true
        type: string
        
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: GetCommitId
        run: |
          pwsh -File ./.github/workflows/getcommitid.ps1 -SourceTag ${{ inputs.Tag }}
        shell: pwsh
     
      - name: print commit id
        run: echo "COMMIT ID IS ${{ env.COMMIT_ID }}"
 
  prod:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v3

      - name: Merging repo
        run: |
          pwsh -File ./mergerepo.ps1 `
               -SourceTag ${{ inputs.Tag }} `
               -TargetBranch prod `
               -svc_repos_email anilathma@cloudeqs.com `
               -svc_repos_username Anilathmacloudeqs
        shell: pwsh
        working-directory: ./.github/workflows
      
      - name: Printing commit ID  
        run: echo "COMMIT ID IS ${{ env.COMMIT_ID }}"
